1 restructure install (#5)
* Moved logging to a separate file.

* Removed logging from install and import scripts/log

* Create new script to install system dependencies.

* Included new file into main script.

* Change message type.

* Added curl to packages.

* Added script to install selene.

* Added messages for user.

* Moved installation of selene to a separate script.

* Added function to install a single package.

* Fixed wrong path.

* Fixed path.

* Take all arguments as installation candidates.

* Added script to install lpeglabel.

* Added return value if installation fails.

* Adapted code to new installation process of lpeglabel.

* Added script to install nerd-fonts.

* Changed code to work with new nerd-fonts code.

* Reset pathes.

* Reset log path.

* Calling main to run the application.

* Auto conformation of updates.

* Renamed package.

* Added correct path of log

* Updated system deps.

* Added dependencies.

* Wrote unique nvim name.

* Added version check for nvim.

* Removed nerd-fonts installation.

* Refactored code for maintainability.

* Install nvim before checking the version.

* Enabled option to run git clone process in background.

* Updated clone process.

* Import nerdfonts script.

* Added error message for this.

* Fixed import root path bug.

* Try to fix path location.

* Added Local path name.

* Fixed not posix conform.

* Handle case if argument 1 is not given.

* Added check to see if script dir is unset.

* Changed structure.

* Removed bullshit.

* Changed to pwd.

* Added executeable

* Changed version check.

* Added constants for version checks.

* Added new check fo system dependencies.

* Adapted selection of packages.

* Added install script if neovim version is not installed.

* Changed return structure.

* Added cmd to install Mason servers and ts.

* Fixed error, to allow test install script.

* Removed useless line and set timeouts.

* Added CARGO_HOME in install file if not in path.

* Added information about the install script to Markdown file.

* Added python3-venv package to install candidates.

* Added npm to installation candidates.

* Added Install instructions to README.md

* Fixed wrong variable name.

* Fixed double slash error in git repo path.

* Set

* Added Path variable directly to nvim.

* Added lua script to install all packages during installation process.

* Added Before installation path.

* Added After installation section.

* Fixed wrong name.

* Added Goal point.

* Added number to .pre-commit-config for better markdown structure.

* Disabled tailwind-tools.

* Changed structure to allow installation of lsp during installation.

* Reset all.

* Hope this works.

* Added Sync wait, so Lsps are installed.

* Comment functions for test.

* Updated package to download for registry.

* Updated Lazy.

* Removed wrong cmd.

* Fixed wrong path.

* Added package name for servername.

* Changed ipairs to pairs.

* Changed print statements.

* Changed logging message.

* Created log messages.

* Changed autocmd to named cmd.

* Fixed name error.

* Renamed file

* Removed check.

* Added development information.

* Moved linter and formater to separat file.

* Added option to install packages with package registry.

* Added same structure like the language servers.

* Removed Synchronous.

* Reloading nvim, after plugin load.

* Reset to autocmd.

* Reset to name command. Since pathes were wrong.

* Renamed file.

* Removed not existing mapping.

* Made table to old style.

* Added sleep to be safe.

* Added new lazy call, which should block.

* New try

* Removed cmd.

* Added new wait for plugins.

* Reset code.

* Reset to old install way.

* Added sleep to test delay.

* Removed sleep

* Check with module is not loaded.

* Checking path errors.

* Added small delay and removed useless code.

* Fixed install

* Moved Lazy sync to cmd.

* Sign this final commit

* Sign this final commit

* Fixed wrong cmd in lua

* Changed print to echo.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,126 +2,57 @@
 
 set -e
 
-log() {
-    LEVEL="$1"
-    shift
-    MSG="$*"
-    TIME=$(date +"%H:%M:%S")
-    case "$LEVEL" in
-        DEBUG) COLOR="\033[37m" ;;
-        INFO) COLOR="\033[34m" ;;
-        SUCCESS) COLOR="\033[32m" ;;
-        WARNING) COLOR="\033[33m" ;;
-        ERROR) COLOR="\033[31m" ;;
-        *) COLOR="\033[0m" ;;
-    esac
-    printf "%b[%s]%b %-7s| %b%s%b\n" "\033[36m" "${TIME}" "${COLOR}" "${LEVEL}" "\033[37m" "${MSG}" "\033[0m"
-}
-debug() {
-    log "DEBUG" "$*"
-}
-info() {
-    log "INFO" "$*"
-}
-success() {
-    log "SUCCESS" "$*"
-}
-warning() {
-    log "WARNING" "$*"
-}
-error() {
-    log "ERROR" "$*"
-}
+MAJOR_REQ=0
+MINOR_REQ=11
+PATCH_REQ=4
 
-install_system_packages() {
-    info "Identifing package manger."
-    if command -v apt-get >/dev/null 2>&1; then
-        PKGS="neovim git gcc clang python3 python3-pip golang nodejs openjdk-21-jdk ninja-build libstdc++-dev luarocks maven g++ pkg-config libssl-dev pre-commit liblua5.4-dev"
-        sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y ${PKGS}
-    elif command -v dnf >/dev/null 2>&1; then
-        PKGS="neovim git gcc clang python python-pip golang nodejs java-latest-openjdk-devel ninja-build libstdc++-static luarocks maven gcc-c++ pkg-config openssl-devel pre-commit lua-devel"
-        sudo dnf update -y && sudo dnf install -y ${PKGS}
+SCRIPT_DIR="$(pwd)/scripts"
 
-    else
-        warning "No valid package manager found."
-        return 1
-    fi
-    success "Using '${PKG_MANAGER}' as package manager."
-    return 0
-}
-
-install_lpeglabel() {
-    if ! command -v lua >/dev/null 2>&1; then
-        error "Lua not installed"
-        return 1
-    fi
-    info "Installing 'lpeglabel"
-    luarocks install lpeglabel --local
-    success "Installed 'lpeglabel'"
-}
-
-install_selene() {
-    info "Installing selene ..."
-    if ! command -v rustc >/dev/null 2>&1; then
-        warning "RUST not installed"
-        debug "Installing RUST."
-        if [ -z "$CARGO_HOME" ]; then
-            export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
-        fi
-        if [ -z "$RUSTUP_HOME" ]; then
-            export RUSTUP_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/rustup"
-        fi
-
-        debug "CARGO will be installed in ${CARGO_HOME}"
-        debug "Rust will be installed in ${RUSTUP_HOME}"
-
-        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
-        info "Installed rust"
-
-        if ! echo ":$PATH:" | grep -q ":$CARGO_HOME/bin:"; then
-            export PATH="$CARGO_HOME/bin:$PATH"
-        fi
-    fi
-    cargo install selene
-    success "Installed selene"
-}
-
-install_nerd_fonts() {
-    if [ "$1" = "--nerd-fonts" ]; then
-        NERDPATH="${HOME}/.local/src"
-        info "Installing nerd-fonts to '${NERDPATH}'"
-
-        git clone https://github.com/ryanoasis/nerd-fonts "${NERDPATH}" || return 1
-        cd "${NERDPATH}"
-        chmod +x install.sh
-        ./install.sh || exit 1
-        success "Installed nerd-fonts."
-        return 0
-    fi
-    info "Skipping nerd-fonts installation."
-    info "Please install nerd-fonts (https://github.com/ryanoasis/nerd-fonts)."
-    return 0
-}
+. "${SCRIPT_DIR}/log"
+. "${SCRIPT_DIR}/install/system-dependencies"
+. "${SCRIPT_DIR}/install/selene"
+. "${SCRIPT_DIR}/install/lpeglabel"
+. "${SCRIPT_DIR}/install/nerd-fonts"
+. "${SCRIPT_DIR}/install/nvim"
 
 main() {
+    if [ "$1" = "--nerd-fonts" ]; then
+        init_clone_process
+        info "Cloning nerd-fonts in background."
+    else
+        info "Skipping nerd-fonts installation."
+        info "Please install nerd-fonts 'https://github.com/ryanoasis/nerd-fonts'."
+    fi
 
-    if ! install_system_packages; then
-        error "Stopping installation. Can't install system packages."
+    if ! install_system_dependencies; then
+        error "Stopping installation. Can't install system dependencies."
+        exit 1
+    fi
+    if ! check_nvim_version; then
+        error "Neovim version v0.11.4 or higher is required.\n
+        Please install it before you can continue with the installation."
         exit 1
     fi
 
-    info "Installing neovim dependencies."
-    install_selene
-
-    info "Installing lazy..."
-    nvim --headless +qa
-
-    info "Installing plugins ... "
-    nvim --headless "+Lazy! sync" +qa
-
-    if ! install_nerd_fonts "$1"; then
-        warning "Could not install nerd-fonts. Continue..."
+    if ! install_selene; then
+        warning "Can not install selene. Continue ..."
     fi
+
+    if ! install_lpeglabel; then
+        warning "Can not install lpeglabel. Continue ..."
+    fi
+
+    info "Installing language-servers, formaters and linters ... "
+    PATH="${CARGO_HOME:-$HOME/.cargo}/bin:$PATH" nvim --headless "+InitNVIM"
+    echo "\n"
+
+    if [ "$1" = "--nerd-fonts" ]; then
+        install_nerd_fonts
+    fi
+
+    info "You need to set a '${CARGO_HOME}/bin' in your path permanently to enable mason future updates."
+    success "Setup nvim successfully. Enjoy it :)"
+    return 0
 }
 
 main "$@"
