Refactored installation process.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -33,14 +33,14 @@ error() {
     log "ERROR" "$*"
 }
 
-get_pck_manager() {
+install_system_packages() {
     info "Identifing package manger."
     if command -v apt-get >/dev/null 2>&1; then
-        PKG_MANAGER="apt-get"
         PKGS="neovim git gcc clang python3 python3-pip golang nodejs openjdk-21-jdk ninja-build libstdc++-dev luarocks maven g++ pkg-config libssl-dev pre-commit liblua5.4-dev"
+        sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y ${PKGS}
     elif command -v dnf >/dev/null 2>&1; then
-        PKG_MANAGER="dnf"
         PKGS="neovim git gcc clang python python-pip golang nodejs java-latest-openjdk-devel ninja-build libstdc++-static luarocks maven gcc-c++ pkg-config openssl-devel pre-commit lua-devel"
+        sudo dnf update -y && sudo dnf install -y ${PKGS}
 
     else
         warning "No valid package manager found."
@@ -94,7 +94,7 @@ install_nerd_fonts() {
         git clone https://github.com/ryanoasis/nerd-fonts "${NERDPATH}" || return 1
         cd "${NERDPATH}"
         chmod +x install.sh
-        ./install.sh ||  exit 1
+        ./install.sh || exit 1
         success "Installed nerd-fonts."
         return 0
     fi
@@ -105,15 +105,12 @@ install_nerd_fonts() {
 
 main() {
 
-    PKG_MANAGER=""
-    PKGS=""
-    if ! get_pck_manager; then
-        error "Stopping installation. Can't install dependencies."
+    if ! install_system_packages; then
+        error "Stopping installation. Can't install system packages."
         exit 1
     fi
 
     info "Installing neovim dependencies."
-    sudo $PKG_MANAGER update -y && sudo $PKG_MANAGER install -y ${PKGS}
     install_selene
 
     info "Installing lazy..."
