Moved installation of rust to dependencies.

diff --git a/scripts/install/shared/install_dependencies b/scripts/install/shared/install_dependencies
--- a/scripts/install/shared/install_dependencies
+++ b/scripts/install/shared/install_dependencies
@@ -4,7 +4,7 @@
 
 . "${SCRIPT_DIR}/log"
 
-install_system_pck() {
+install_packages_with_pkg_mgr() {
     if [ ! -z "${PKG_MGR}" ]; then
         warning "Need to set 'PKG_MGR', or call 'identify_system_pkg_mgr'."
         return 3
@@ -45,5 +45,25 @@ identify_system_pkg_mgr() {
         debug "Package manager was already defined as '${PKG_MGR}'"
     fi
     success "Identified '${PKG_MGR}' as package manager."
+    return 0
+}
+
+install_rust() {
+    if command -v rustc >/dev/null 2>&1; then
+        info "Rust is already installed."
+        return 0
+    fi
+
+    CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
+    debug "CARGO_HOME is set to '${CARGO_HOME}'."
+
+    info "Downloading and install rust..."
+    if ! curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y; then
+        error "Installation of rust failed."
+        return 1
+    fi
+    echo ":$PATH:" | grep -q ":${CARGO_HOME}/bin:" || export PATH="${CARGO_HOME}/bin:${PATH}"
+
+    success "Installed rust."
     return 0
 }
