Refactored nerdfonts process.

diff --git a/installs/nerd-fonts b/installs/nerd-fonts
--- a/installs/nerd-fonts
+++ b/installs/nerd-fonts
@@ -4,54 +4,43 @@ SCRIPT_DIR="${SCRIPT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
 
 source "${SCRIPT_DIR}/utils" || exit 1
 
-TMPFILE=$(mktemp)
-NERD_FONTS_PROCESS=""
+TMPFILE=""
+NERD_FONTS_PID=""
 
-clone_repo() {
-    debug "Cloning repo to '${NERDPATH}'"
-    git clone --progress https://github.com/ryanoasis/nerd-fonts "${NERDPATH}" >"$TMPFILE" 2>&1 & NERD_FONTS_PROCESS=$!
-    info "Cloned repo"
-}
+init_new() {
+    local git_dest_dir="${XDG_DATA_HOME:-$HOME/.local/share}/src"
+    NERD_FONTS_DIR="${git_dest_dir}/nerd-fonts"
 
-pull_repo() {
-    if git -C "${NERDPATH}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
-        debug "${NERDPATH} is a git repo."
-        cd "${NERDPATH}" || return 1
-        git pull >"$TMPFILE" 2>&1 & NERD_FONTS_PROCESS=$!
-        info "Pulling repo."
+    if [ -d "${NERD_FONTS_DIR}" ] && dir_is_git_repo "${NERD_FONTS_DIR}"; then
+        debug "Nerd-fonts git repo exists. Pulling ..."
+        pull_git_dir "${NERD_FONTS_DIR}" || return 2
+        return 0
+    elif [ ! -d "${NERD_FONTS_DIR}" ]; then
+        debug "Nerd-fonts git repo not exists. Cloning ..."
+        read -r NERD_FONTS_PID TMPFILE < <(clone_repo https://github.com/ryanoasis/nerd-fonts "${NERD_FONTS_DIR}")
+        status=$?
+        if [ "${status}" -ne 0 ]; then
+            error "clone_repo function failed!"
+            return 3
+        fi
+        printf pid
+        return 0
     else
-        warning "${NERDPATH} is not a git repo. Can not pull ..."
+        error "Directory ${NERD_FONTS_DIR} already exists and is no git repo."
+        return 1
     fi
-}
-
-init_nerd_process() {
-    NERDPATH="${XDG_DATA_HOME:-$HOME/.local/share}/src/nerd-fonts"
-    if [ -d "${NERDPATH}" ]; then
-        pull_repo
-    else
-        mkdir -p "${NERDPATH}"
-        clone_repo
-    fi
-    info "Started nerd-fonts process ${NERD_FONTS_PROCESS}"
-}
-
-wait_for_nerd_fonts_process() {
-    info "Waiting for clone process to finish"
-    tail -f "${TMPFILE}"
-    wait "${NERD_FONTS_PROCESS}"
 }
 
 kill_nerd_fonts_process() {
-    if ! kill "${NERD_FONTS_PROCESS}"; then
-        warning "Can not kill nerd-fonts process '${NERD_FONTS_PROCESS}'."
+    if ! kill "${NERD_FONTS_PID}"; then
+        warning "Can not kill nerd-fonts process '${NERD_FONTS_PID}'."
     fi
 }
 
 install_nerd_fonts() {
-    wait_for_nerd_fonts_process
-
-    cd "${NERDPATH}" || return 1
-    chmod +x install.sh
+    wait_for_clone_process "${NERD_FONTS_PID}" "${TMPFILE}" || exit 2
+    [ -z "${NERD_FONTS_DIR}" ] && warning "Not Nerd-fonts directory defined." && exit 2
+    cd "${NERD_FONTS_DIR}" && chmod +x install.sh || return 1
     ./install.sh || return 1
     success "Installed nerd-fonts."
     return 0
