Code added to generate uniform test output

diff --git a/env/entrypoint b/env/entrypoint
--- a/env/entrypoint
+++ b/env/entrypoint
@@ -1,8 +1,11 @@
 #!/usr/bin/bash
 
 RESET="\033[0m"
-RED="\033[31m"
+BOLD="\033[1m"
+RED="\033[91m"
 GREEN="\033[92m"
+ORANGE="\033[33m"
+CYAN="\033[94m"
 
 BASH_TESTS_DIR="${NVIM_CONFIG}/tests/bash"
 
@@ -54,7 +57,7 @@ function print_wrong_output() {
     local print_next=0
     while IFS= read -r line; do
         if [[ $line =~ ^not\ ok\ ([0-9]+)\ (.*) ]]; then
-            printf "[TEST] %s: %s\n" "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}"
+            printf "%b[TEST]%b %b%3s%b: %b%s%b\n" "${RED}" "${RESET}" "${BOLD}" "${BASH_REMATCH[1]}" "${RESET}" "${ORANGE}" "${BASH_REMATCH[2]}" "${RESET}"
             print_next=1
         elif [[ $print_next -eq 1 && $line =~ ^# ]]; then
             printf "%s\n" "${line}"
@@ -74,11 +77,12 @@ function get_test_counter() {
 function main() {
     get_bash_test_files
 
+    local failures=false
     local width=10
     for test in "${BASH_TEST_FILES[@]}"; do
         if [[ ${#test} -gt $width ]]; then
             width=${#test}
-            if [[ ${#test} ]]; then
+            if [[ $((width % 2)) -eq 1 ]]; then
                 width=$((width + 1))
             fi
         fi
@@ -90,28 +94,50 @@ function main() {
     string=$(printf '%.0s'"${char}" $(seq 1 $(((width + 18) / 2))))
 
     printf "%s Starting Tests %s\n" "${string}" "${string}"
-    printf "Collected %d tests\n" "$(get_test_counter)"
+    printf "Collected %b%d%b tests\n" "${BOLD}" "$(get_test_counter)" "${RESET}"
 
     for test in "${BASH_TEST_FILES[@]}"; do
         execute_bash_test "${test}"
         index=$(("${#BASH_STATUS_TESTS[@]}" - 1))
-        printf "[TEST]: %-*s" "${width}" "${test}"
+        printf "%b[FILE]%b: %-*s" "${CYAN}" "${BOLD}" "${width}" "${test}"
 
         if [[ ${BASH_COUNTER_FAILURE_TESTS[${index}]} -gt 0 ]]; then
+            failures=true
             printf "%b" "${RED}"
         else
             printf "%b" "${GREEN}"
         fi
 
-        printf "%-2d passed / %-2d failure" "${BASH_COUNTER_SUCCESS_TESTS[${index}]}" "${BASH_COUNTER_FAILURE_TESTS[${index}]}"
+        printf "%-3d passed / %3d failure" "${BASH_COUNTER_SUCCESS_TESTS[${index}]}" "${BASH_COUNTER_FAILURE_TESTS[${index}]}"
 
         if [[ ${BASH_COUNTER_FAILURE_TESTS[${index}]} -gt 0 ]]; then
             printf "  %b" "${RESET}"
         else
             printf "  %b" "${RESET}"
         fi
-
         printf "\n"
+    done
+
+    char="="
+    string=$(printf '%.0s'"${char}" $(seq 1 $(((width + 24) / 2))))
+    if ${failures}; then
+        printf "%s FAILURES %s\n" "${string}" "${string}"
+    else
+        printf "%s%s%s\n" "${string}" "==========" "${string}"
+    fi
+
+
+    char="-"
+    string=$(printf '%.0s'"${char}" $(seq 1 $((width + 34))))
+    for i in "${!BASH_TEST_FILES[@]}"; do
+        if ! ${failures}; then
+            printf "%s\n" "${string}"
+        fi
+        if [[ ${BASH_STATUS_TESTS[${i}]} -ne 0 ]]; then
+            failures=true
+            printf "%b[FILE]%b: %s\n" "${CYAN}" "${BOLD}" "${BASH_TEST_FILES[${i}]}"
+            print_wrong_output "${BASH_OUTPUT_TESTS[$i]}"
+        fi
     done
 
 }
